ActiveSupport::Inflector.inflections do |inflect|
  inflect.irregular 'actor', 'actores'
  inflect.irregular 'convenio', 'convenios'
  inflect.irregular 'informeauditoria', 'informeauditorias'
  inflect.irregular 'mindicadorpf', 'mindicadorespf'
  inflect.irregular 'nivelrelacion', 'nivelesrelacion'
  inflect.irregular 'nucleoconflicto', 'nucleosconflicto'
  inflect.irregular 'perfilprofesional', 'perfilesprofesionales'
  inflect.irregular 'redactor', 'redesactor'
  inflect.irregular 'regiongrupo', 'regionesgrupo'
  inflect.irregular 'sectoractor', 'sectoresactores'
  inflect.irregular 'tasacambio', 'tasascambio'
  inflect.irregular 'tipoanexo', 'tiposanexo'
  inflect.irregular 'tipoconvenio', 'tiposconvenio'
  inflect.irregular 'tipomoneda', 'tiposmoneda'
  inflect.irregular 'tipoproductopf', 'tiposproductopf'
end
