class EtiquetaPdet < ActiveRecord::Migration[6.1]
  def up
    e = Sip::Etiqueta.create!(
      id: 15,
      nombre: 'Municipio PDET 2021',
      observaciones: 'Usado en medicion de indicadores Plan Trienal 2021-2023',
      fechacreacion: Date.today
    )

    execute <<-SQL
      INSERT INTO sip_etiqueta_municipio (etiqueta_id, municipio_id) 
        (SELECT 15, m.id  FROM
          (SELECT  * FROM (VALUES
            (1, 'CAUCA', 'ARGELIA'),
            (2, 'CAUCA', 'BALBOA'),
            (3, 'CAUCA', 'CAJIBÍO'),
            (4, 'CAUCA', 'EL TAMBO'),
            (5, 'CAUCA', 'MERCADERES'),
            (6, 'CAUCA', 'PATÍA'),
            (7, 'NARIÑO', 'CUMBITARA'),
            (8, 'NARIÑO', 'EL ROSARIO'),
            (9, 'NARIÑO', 'LEIVA'),
            (10, 'NARIÑO', 'LOS ANDES'),
            (11, 'NARIÑO', 'POLICARPA'),
            (12, 'CAUCA', 'BUENOS AIRES'),
            (13, 'CAUCA', 'CALOTO'),
            (14, 'CAUCA', 'JAMBALÓ'),
            (15, 'CAUCA', 'MIRANDA'),
            (16, 'CAUCA', 'MORALES'),
            (17, 'CAUCA', 'PIENDAMÓ - TUNÍA'),
            (18, 'CAUCA', 'SANTANDER DE QUILICHAO'),
            (19, 'CAUCA', 'SUÁREZ'),
            (20, 'CAUCA', 'TORIBÍO'),
            (21, 'CAUCA', 'CALDONO'),
            (22, 'CAUCA', 'CORINTO'),
            (23, 'VALLE DEL CAUCA', 'FLORIDA'),
            (24, 'VALLE DEL CAUCA', 'PRADERA'),
            (25, 'ARAUCA', 'ARAUQUITA'),
            (26, 'ARAUCA', 'FORTUL'),
            (27, 'ARAUCA', 'SARAVENA'),
            (28, 'ARAUCA', 'TAME'),
            (29, 'ANTIOQUIA', 'AMALFI'),
            (30, 'ANTIOQUIA', 'ANORÍ'),
            (31, 'ANTIOQUIA', 'BRICEÑO'),
            (32, 'ANTIOQUIA', 'CÁCERES'),
            (33, 'ANTIOQUIA', 'CAUCASIA'),
            (34, 'ANTIOQUIA', 'EL BAGRE'),
            (35, 'ANTIOQUIA', 'ITUANGO'),
            (36, 'ANTIOQUIA', 'NECHÍ'),
            (37, 'ANTIOQUIA', 'REMEDIOS'),
            (38, 'ANTIOQUIA', 'SEGOVIA'),
            (39, 'ANTIOQUIA', 'TARAZÁ'),
            (40, 'ANTIOQUIA', 'VALDIVIA'),
            (41, 'ANTIOQUIA', 'ZARAGOZA'),
            (42, 'NORTE DE SANTANDER', 'CONVENCIÓN'),
            (43, 'NORTE DE SANTANDER', 'EL CARMEN'),
            (44, 'NORTE DE SANTANDER', 'EL TARRA'),
            (45, 'NORTE DE SANTANDER', 'HACARÍ'),
            (46, 'NORTE DE SANTANDER', 'SAN CALIXTO'),
            (47, 'NORTE DE SANTANDER', 'SARDINATA'),
            (48, 'NORTE DE SANTANDER', 'TEORAMA'),
            (49, 'NORTE DE SANTANDER', 'TIBÚ'),
            (50, 'CAQUETÁ', 'FLORENCIA'),
            (51, 'CAQUETÁ', 'ALBANIA'),
            (52, 'CAQUETÁ', 'BELÉN DE LOS ANDAQUÍES'),
            (53, 'CAQUETÁ', 'CARTAGENA DEL CHAIRÁ'),
            (54, 'CAQUETÁ', 'CURILLO'),
            (55, 'CAQUETÁ', 'EL DONCELLO'),
            (56, 'CAQUETÁ', 'EL PAUJÍL'),
            (57, 'CAQUETÁ', 'LA MONTAÑITA'),
            (58, 'CAQUETÁ', 'MILÁN'),
            (59, 'CAQUETÁ', 'MORELIA'),
            (60, 'CAQUETÁ', 'PUERTO RICO'),
            (61, 'CAQUETÁ', 'SAN JOSÉ DEL FRAGUA'),
            (62, 'CAQUETÁ', 'SAN VICENTE DEL CAGUÁN'),
            (63, 'CAQUETÁ', 'SOLANO'),
            (64, 'CAQUETÁ', 'SOLITA'),
            (65, 'CAQUETÁ', 'VALPARAÍSO'),
            (66, 'HUILA', 'ALGECIRAS'),
            (67, 'META', 'MAPIRIPÁN'),
            (68, 'META', 'MESETAS'),
            (69, 'META', 'LA MACARENA'),
            (70, 'META', 'URIBE'),
            (71, 'META', 'PUERTO CONCORDIA'),
            (72, 'META', 'PUERTO LLERAS'),
            (73, 'META', 'PUERTO RICO'),
            (74, 'META', 'VISTAHERMOSA'),
            (75, 'GUAVIARE', 'SAN JOSÉ DEL GUAVIARE'),
            (76, 'GUAVIARE', 'CALAMAR'),
            (77, 'GUAVIARE', 'EL RETORNO'),
            (78, 'GUAVIARE', 'MIRAFLORES'),
            (79, 'BOLÍVAR', 'CÓRDOBA'),
            (80, 'BOLÍVAR', 'EL CARMEN DE BOLÍVAR'),
            (81, 'BOLÍVAR', 'EL GUAMO'),
            (82, 'BOLÍVAR', 'MARÍA LA BAJA'),
            (83, 'BOLÍVAR', 'SAN JACINTO'),
            (84, 'BOLÍVAR', 'SAN JUAN NEPOMUCENO'),
            (85, 'BOLÍVAR', 'ZAMBRANO'),
            (86, 'SUCRE', 'COLOSÓ'),
            (87, 'SUCRE', 'CHALÁN'),
            (88, 'SUCRE', 'LOS PALMITOS'),
            (89, 'SUCRE', 'MORROA'),
            (90, 'SUCRE', 'OVEJAS'),
            (91, 'SUCRE', 'PALMITO'),
            (92, 'SUCRE', 'SAN ONOFRE'),
            (93, 'SUCRE', 'SAN JOSÉ DE TOLUVIEJO (TOLÚ VIEJO)'),
            (94, 'CAUCA', 'GUAPI'),
            (95, 'CAUCA', 'LÓPEZ DE MICAY'),
            (96, 'CAUCA', 'TIMBIQUÍ'),
            (97, 'VALLE DEL CAUCA', 'BUENAVENTURA'),
            (98, 'NARIÑO', 'BARBACOAS'),
            (99, 'NARIÑO', 'EL CHARCO'),
            (100, 'NARIÑO', 'LA TOLA'),
            (101, 'NARIÑO', 'MAGÜÍ'),
            (102, 'NARIÑO', 'MOSQUERA'),
            (103, 'NARIÑO', 'OLAYA HERRERA'),
            (104, 'NARIÑO', 'FRANCISCO PIZARRO'),
            (105, 'NARIÑO', 'RICAURTE'),
            (106, 'NARIÑO', 'ROBERTO PAYÁN'),
            (107, 'NARIÑO', 'SANTA BÁRBARA'),
            (108, 'NARIÑO', 'SAN ANDRÉS DE TUMACO'),
            (109, 'PUTUMAYO', 'MOCOA'),
            (110, 'PUTUMAYO', 'ORITO'),
            (111, 'PUTUMAYO', 'PUERTO ASÍS'),
            (112, 'PUTUMAYO', 'PUERTO CAICEDO'),
            (113, 'PUTUMAYO', 'PUERTO GUZMÁN'),
            (114, 'PUTUMAYO', 'PUERTO LEGUÍZAMO'),
            (115, 'PUTUMAYO', 'SAN MIGUEL'),
            (116, 'PUTUMAYO', 'VALLE DEL GUAMUEZ'),
            (117, 'PUTUMAYO', 'VILLAGARZÓN'),
            (118, 'CESAR', 'VALLEDUPAR'),
            (119, 'CESAR', 'AGUSTÍN CODAZZI'),
            (120, 'CESAR', 'BECERRIL'),
            (121, 'CESAR', 'LA JAGUA DE IBIRICO'),
            (122, 'CESAR', 'PUEBLO BELLO'),
            (123, 'CESAR', 'LA PAZ'),
            (124, 'CESAR', 'SAN DIEGO'),
            (125, 'CESAR', 'MANAURE BALCÓN DEL CESAR'),
            (126, 'LA GUAJIRA', 'DIBULLA'),
            (127, 'LA GUAJIRA', 'FONSECA'),
            (128, 'LA GUAJIRA', 'SAN JUAN DEL CESAR'),
            (129, 'MAGDALENA', 'ARACATACA'),
            (130, 'MAGDALENA', 'CIÉNAGA'),
            (131, 'MAGDALENA', 'FUNDACIÓN'),
            (132, 'MAGDALENA', 'SANTA MARTA'),
            (133, 'ANTIOQUIA', 'YONDÓ'),
            (134, 'BOLÍVAR', 'ARENAL'),
            (135, 'BOLÍVAR', 'CANTAGALLO'),
            (136, 'BOLÍVAR', 'MORALES'),
            (137, 'BOLÍVAR', 'SAN PABLO'),
            (138, 'BOLÍVAR', 'SANTA ROSA DEL SUR'),
            (139, 'BOLÍVAR', 'SIMITÍ'),
            (140, 'CÓRDOBA', 'MONTELÍBANO'),
            (141, 'CÓRDOBA', 'PUERTO LIBERTADOR'),
            (142, 'CÓRDOBA', 'SAN JOSÉ DE URÉ'),
            (143, 'CÓRDOBA', 'TIERRALTA'),
            (144, 'CÓRDOBA', 'VALENCIA'),
            (145, 'TOLIMA', 'ATACO'),
            (146, 'TOLIMA', 'CHAPARRAL'),
            (147, 'TOLIMA', 'PLANADAS'),
            (148, 'TOLIMA', 'RIOBLANCO'),
            (149, 'ANTIOQUIA', 'APARTADÓ'),
            (150, 'ANTIOQUIA', 'CAREPA'),
            (151, 'ANTIOQUIA', 'CHIGORODÓ'),
            (152, 'ANTIOQUIA', 'MUTATÁ'),
            (153, 'ANTIOQUIA', 'NECOCLÍ'),
            (154, 'ANTIOQUIA', 'SAN PEDRO DE URABÁ'),
            (155, 'ANTIOQUIA', 'TURBO'),
            (156, 'ANTIOQUIA', 'DABEIBA'),
            (157, 'CHOCÓ', 'ACANDÍ'),
            (158, 'CHOCÓ', 'UNGUÍA'),
            (159, 'CHOCÓ', 'CARMEN DEL DARIÉN'),
            (160, 'CHOCÓ', 'RIOSUCIO'),
            (161, 'CHOCÓ', 'BOJAYÁ'),
            (162, 'CHOCÓ', 'MEDIO ATRATO'),
            (163, 'ANTIOQUIA', 'VIGÍA DEL FUERTE'),
            (164, 'CHOCÓ', 'CONDOTO'),
            (165, 'CHOCÓ', 'EL LITORAL DEL SAN JUAN'),
            (166, 'CHOCÓ', 'ISTMINA'),
            (167, 'CHOCÓ', 'MEDIO SAN JUAN'),
            (168, 'ANTIOQUIA', 'MURINDÓ'),
            (169, 'CHOCÓ', 'NÓVITA'),
            (170, 'CHOCÓ', 'SIPÍ')
          ) AS da (num, dep, mun)) AS da
        LEFT JOIN sip_departamento AS de ON
        de.nombre=da.dep AND de.id_pais=170
        LEFT JOIN sip_municipio AS m ON
        de.id=m.id_departamento AND m.nombre=da.mun
        ORDER BY 1)
      ;
    SQL
  end


  def down
    execute <<-SQL
      DELETE FROM sip_etiqueta_municipio WHERE etiqueta_id=15;
      DELETE FROM sip_etiqueta WHERE etiqueta_id=15;
    SQL
  end
end
